"""fix db

Revision ID: 700b9f0cb5ae
Revises: 865d210c9377
Create Date: 2025-03-31 17:55:30.220889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700b9f0cb5ae'
down_revision = '865d210c9377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_tx', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('raw_tx')

    # ### end Alembic commands ###
